// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFF4Red5NVzRob85u7f1Rfs3q6ioZu7Ls',
    appId: '1:311891289894:web:5d1e6ba748ed11b02903e7',
    messagingSenderId: '311891289894',
    projectId: 'vick-s-e036a',
    authDomain: 'vick-s-e036a.firebaseapp.com',
    storageBucket: 'vick-s-e036a.firebasestorage.app',
    measurementId: 'G-X3VM8RL63Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJnYhP-38g9BNE7MXFnNyMU_PSlMlgYVo',
    appId: '1:311891289894:android:5a8c32cd9a4b02492903e7',
    messagingSenderId: '311891289894',
    projectId: 'vick-s-e036a',
    storageBucket: 'vick-s-e036a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAk91aJustjwTsusAkrbltlq_NVKnTolM',
    appId: '1:311891289894:ios:cf6dc0a129d6f6872903e7',
    messagingSenderId: '311891289894',
    projectId: 'vick-s-e036a',
    storageBucket: 'vick-s-e036a.firebasestorage.app',
    iosBundleId: 'com.example.vickFerreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAk91aJustjwTsusAkrbltlq_NVKnTolM',
    appId: '1:311891289894:ios:cf6dc0a129d6f6872903e7',
    messagingSenderId: '311891289894',
    projectId: 'vick-s-e036a',
    storageBucket: 'vick-s-e036a.firebasestorage.app',
    iosBundleId: 'com.example.vickFerreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFF4Red5NVzRob85u7f1Rfs3q6ioZu7Ls',
    appId: '1:311891289894:web:578febee60c5e36a2903e7',
    messagingSenderId: '311891289894',
    projectId: 'vick-s-e036a',
    authDomain: 'vick-s-e036a.firebaseapp.com',
    storageBucket: 'vick-s-e036a.firebasestorage.app',
    measurementId: 'G-KY7MQM2BMJ',
  );
}
